name: Build Verification

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.9.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # Windows에서 필요한 추가 설정
      - name: Setup Visual Studio for Windows builds
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          echo "Setting up VS environment variables"
        env:
          npm_config_msvs_version: 2019

      # 환경 변수 설정
      - name: Setup environment variables
        run: node .github/workflows/env-setup.js

      - name: Build application
        run: pnpm build
        env:
          npm_config_msvs_version: 2019
          GH_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # Electron 빌더 실행 (패키징만, 게시 안 함)
      - name: Package Electron App
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --win --config electron-builder.config.js --publish never
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          npm_config_msvs_version: 2019

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/
          retention-days: 7
